python2 and tabs to spaces

diff --git a/scripts/backup-generic b/scripts/backup-generic
--- a/scripts/backup-generic
+++ b/scripts/backup-generic
@@ -7,25 +7,25 @@ renice -n 19 -p $$ > /dev/null
 (
 # Only allow one backup to run at a time
 if ! flock -n -x 200; then
-	echo "Failed to get a lock!"
-	exit 1
+    echo "Failed to get a lock!"
+    exit 1
 fi
 
 # Exclude other filesystems from the backup. This leaves only the files we
 # want, on the root file system, to back up.
 # Also exclude other large collections of files which we don't care to save.
 rdiff-backup \
-	--preserve-numerical-ids \
-	--exclude-sockets \
-	--exclude '/home/*/tmp' \
-	--include '/home' \
-	--exclude '/backup' \
-	--exclude '/tmp' \
-	--exclude '/var/cache' \
-	--exclude '/var/log' \
-	--include '/var' \
-	--exclude-other-filesystems \
-	/ /backup/
+    --preserve-numerical-ids \
+    --exclude-sockets \
+    --exclude '/home/*/tmp' \
+    --include '/home' \
+    --exclude '/backup' \
+    --exclude '/tmp' \
+    --exclude '/var/cache' \
+    --exclude '/var/log' \
+    --include '/var' \
+    --exclude-other-filesystems \
+    / /backup/
 
 
 # Remove old backups to free up some space
